# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# This pipeline will be extended to the MicroBuild template
# The Task 'PublishBuildArtifacts@1' has been converted to an output named 'Publish Artifact: NuGet' in the templateContext section.
trigger: none
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/dev
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release
name: $(Date:yyyyMMdd).$(Rev:r)
variables:
- name: BuildConfiguration
  value: Release
- name: Codeql.Enabled
  value: true
- name: SignType
  value: Real
- name: TeamName
  value: IISWacExtension
- name: version
  value: 0.2.$(Build.BuildNumber)
extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: <AgentPoolPlaceHolder>
    pool:
      name: AzurePipelines-EO
      image: AzurePipelinesWindows2022compliantGPT
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: Job_1
        displayName: 'Build '
        pool:
          name: VSEngSS-MicroBuild2022-1ES
        templateContext:
          mb:
            signing:
              enabled: true
              signType: $(SignType)
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish Artifact: NuGet'
            targetPath: $(Build.SourcesDirectory)\dist\msft.iis.iis-management.$(version).nupkg
            artifactName: NuGet
        steps:
        - checkout: self
          fetchTags: false
        - task: NuGetToolInstaller@1
          displayName: 'Use NuGet '
        - task: NuGetCommand@2
          displayName: NuGet restore
          inputs:
            solution: packages.config
            selectOrConfig: config
            nugetConfigPath: nuget.config
        - task: CmdLine@2
          displayName: Install gulp
          inputs:
            script: |
              npm install --global gulp-cli
            workingDirectory: src
        - task: CmdLine@2
          displayName: Install packages
          inputs:
            script: |
              npm install
            workingDirectory: src
        - task: CmdLine@2
          displayName: Run npm audit fix
          inputs:
            script: |
              npm audit fix --legacy-peer-deps
            workingDirectory: src
        - task: PowerShell@2
          displayName: PowerShell Script - Build Source
          inputs:
            filePath: build.ps1
          env:
            PATH: $(PATH);$(APPDATA)\npm
        - task: PowerShell@2
          displayName: PowerShell Script - Build NuGet
          inputs:
            filePath: build.ps1
            arguments: --pack --output-hashing all --version=$(version)
          env:
            PATH: $(PATH);$(APPDATA)\npm
        - task: MSBuild@1
          displayName: Sign NuGet Package
          inputs:
            solution: BuildNuGet.signproj
            msbuildArchitecture: x64
            configuration: Release
            msbuildArguments: /p:SignType=$(SignType)