jobs:
- job: build
  pool:
    name: 'Hosted VS2017'  # name of the pool to run this job in
    demands: 
      - msbuild
      - visualstudio
      - vstest
  steps:
  - checkout: self  
    clean: false
    submodules: true  # set to 'true' for a single level of submodules or 'recursive' to get submodules of submodules

  - task: NodeTool@0
    inputs:
      versionSpec: 8.15.0

  - task: NuGetToolInstaller@0
    displayName: 'Install Nuget tool'

  - task: PowerShell@2
    displayName: 'PowerShell Script build.ps1'
    inputs:
      targetType: filePath
      filePath: ./build.ps1
      arguments: '--env=wac --pack --version=0.1.$(Build.BuildNumber) --output-hashing ALL'
