resources:
- repo: self

pool:
  name: 'Hosted VS2017' # name of the pool to run this job in

steps:
- task: PowerShell@2
  displayName: 'PowerShell Script'
  inputs:
    targetType: ./
    filePath: build.ps1
    arguments: '--env=wac --pack'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: '$(Build.SourcesDirectory)/**/*.nupkg;!$(Build.SourcesDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'IIS-WAC-MyGet'
